### ISSUE TITLE
Vagrant shared folder?

### ISSUE THREAD

**Issue by MathieuDoyon** [pilu/fresh#21]
I'm trying to build y app in a Vagrant box with shared folder between the VM and my local computer. However Fresh doesn't seem to rebuild when I edit files locally.

Has anyone experienced something similar?

**Comment by ifraixedes** [comment]
I think that it's not a problem of `fresh`.

In vagrant you can synchronise you folder with different mechanisms; I've tested 2, the native virtualbox mechanism and NFS.

I've discarded the native one, it was so slow when I was accessing to the files inside the virtual machine.

NFS works quite well for those reading and writing files, however if the modification of the files are in the host machine, the changes are received in the virtual machine with some delay.

In my case, I've seen how other watchers take almost nothing for the first one or two writes, but after the delay increases up to 20 seconds, so it's not useful as you have to wait 20 seconds each time that you write in a the directory which is watched.

I don't face this problem that much because, I work inside the virtual machine, connected by ssh, therefore I work through the terminal, however I took a look a little bit, long time ago because some colleagues work in the host machine, but I couldn't find anything that allows to force the synchronisation or change the scan rate of NFS.

Another solution that some people use, although I haven't tried, is to use rsync as a synchronisation mechanism, and it may work because rsync with a local ssh to transfer the most of the times a small change in file should be very fast, however I don't like the solution because I have to copy all the projects witch I'm working from the host machine to the virtual machine, increasing significantly the virtual disk space.

If you try rsync, please let us know if works for this cases (watchers) in acceptable conditions.

**Comment by evt** [comment]
Works fine with vagrant rsync-auto running.

**Comment by ifraixedes** [comment]
@evt brilliant, thanks for letting us know.
